### ISSUE TITLE
Wallet fully unlocks after sending coins 

### ISSUE THREAD

**Issue by gdiscord** [rupaya-project/rupx#2]
This issue tracker is only for technical issues related to RUPAYA Core.
General RUPAYA questions and/or support requests and are best directed to the [RUPAYA Discord](https://discord.rupx.io).

### Describe the issue
the wallet fully unlocks after you send coins, and you have to manually lock and unlock again for staking only
### Can you reliably reproduce the issue?
yes
#### If so, please list the steps to reproduce below:
1. Unlock wallet for staking only
2. Go through the process of sending coins
3. 

### Expected behavior
Wallet should remain unlocked for staking only after coins are sent

### Actual behavior
Wallet fully unlocks after send

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of RUPAYA Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by mo-bay** [comment]
This issue should be resolved in the next wallet update
