### ISSUE TITLE
MN LOST FUNDS: DELETE OLD PROJECT

### ISSUE THREAD

**Issue by leshacat** [rupaya-project/rupx#4]
REMOVE THE OLD PROJECT https://github.com/rupaya-project/rupaya

I JUST INSTALLED THE OLD WALLET AND SEND 10,500 RUPX TO IT....

NEVER GOT FUNDS, JOINED SUPPORT FOR EXCHANGE THEY SAY I SEND TO OLD WALLET

YOU NEED TO DELETE OLD PROJECTS, AND MAKE OLD ADDRESSES INVALID

YOU NEED TO UPDATE YOUR GITHUB LINKS EVERYWHERE AND DELETE REPOSITORIES THAT ARE REPLACED OR MOVED

HOW I GET MY $130+ USD BACK?

0.017271 Bitcoin equals
110.59 United States Dollar

https://find.rupx.io/transaction/36bbd58d07c9f1d7b308eaa742ae030ad75f287611642944bce1b7d296bbab73

**Comment by leshacat** [comment]
So sad :'( no idea waht to do :( sorry I go smoke a joint.

I spent all night long making sure everything went right, researching it and installing wallet...

**Huge blow to my confidence and portfolio**

**Comment by mo-bay** [comment]
Sorry to hear about that, the old repository in clearly marked as Archived

**Comment by mo-bay** [comment]
I am going to close this issue here please head over to our Discord Server : https://discord.gg/tJ3UWSP

**Comment by leshacat** [comment]
> Sorry to hear about that, the old repository in clearly marked as Archived

That is the thing, **it is NOT clearly marked as archived.** It may be _marked as archived_ but there is 0 notice or warning at all about this fork.

This is irresponsible in my opinion.

There is nothing I can do?
